# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.CharField(max_length=30, null=True)),
                ('sales', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('screen', models.IntegerField()),
                ('playcounts', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.CharField(blank=True, max_length=30, null=True)),
                ('attendance', models.CharField(max_length=50)),
                ('daily_attendance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pastbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.CharField(max_length=30, null=True)),
                ('attendance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
