# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.CharField(max_length=30, null=True)),
                ('attendance', models.CharField(max_length=50)),
                ('daily_attendance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pastbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.TextField()),
                ('img', models.TextField()),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.CharField(max_length=30, null=True)),
                ('attendance', models.CharField(max_length=50)),
            ],
        ),
    ]
