# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_livebox_pastbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livebox',
            name='href',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livebox',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livebox',
            name='pubDate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
