# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=300, null=True)),
                ('pubDate', models.CharField(max_length=30, null=True)),
                ('actors', models.CharField(max_length=300, null=True)),
                ('director', models.CharField(max_length=30, null=True)),
                ('userRating', models.CharField(max_length=20, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
