# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.CharField(max_length=30, null=True)),
                ('sales', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('screen', models.IntegerField()),
                ('playcounts', models.IntegerField()),
            ],
        ),
    ]
